-- should be at top
require("gautam.plugins-setup")

require("gautam.core.options")
require("gautam.core.keymaps")
require("gautam.core.colorscheme")
require("gautam.plugins.comment")
require("gautam.plugins.nvim-tree")
require("gautam.plugins.lualine")
require("gautam.plugins.telescope")
require("gautam.plugins.nvim-cmp")
require("gautam.plugins.autopairs")
require("gautam.plugins.gitsigns")
require("gautam.plugins.treesitter")
require("gautam.plugins.lsp.mason")
require("gautam.plugins.lsp.lspsaga")
require("gautam.plugins.lsp.lspconfig")
require("gautam.plugins.lsp.null-ls")
